### ISSUE TITLE
Add Upcase (once the repo is public)

### ISSUE THREAD

**Issue by andyw8** [eliotsykes/real-world-rails#264]
[Upcase](https://thoughtbot.com/upcase/) was open-sourced, but it's currently a private repo only available to ex-subscribers. I believe the intention is to make is public eventually, so once that happens it would be a great addition here.

https://github.com/thoughtbot/upcase

cc @christoomey

**Comment by christoomey** [comment]
@andyw8 Thanks for thinking of us! We do intend to open up Upcase (and the other related repos) and I'll be sure to comment back here when that happens.
