### ISSUE TITLE
Add standard_notes

### ISSUE THREAD

**Issue by andyw8** [eliotsykes/real-world-rails#405]
https://github.com/standardnotes/web

**Comment by eliotsykes** [comment]
Thanks @andyw8. I was excited to add this, then after reviewing what is in it, I'm not so sure. The Rails portion of the app is slim. I'm still very open to adding it if there's something valuable in here for devs to learn about Rails, I just need an idea of what that something is.

**Comment by andyw8** [comment]
Ok, I hadn't looked at it in detail.
