### ISSUE TITLE
No feedback from analyze commands

### ISSUE THREAD

**Issue by Andrehatlo** [eliotsykes/real-world-rails#413]
I followed the instructions as described in `readme`, when trying to run every single example command in the analyze section i get no feedback.
Also, when going through the `/app` folder each repo only includes a `.git` file.
Have i missed something?

**Comment by eliotsykes** [comment]
> Also, when going through the /app folder each repo only includes a .git file. Have i missed something?

I expect this was due to the missing repo you reported in #412. Now that issue is fixed, try starting over with:

```sh
cd real-world-rails
git pull
git submodule update --init
```

**Comment by eliotsykes** [comment]
Please reopen if this is still an issue.
