### ISSUE TITLE
Get your act together and start a newsletter to share findings with wider Rails community

### ISSUE THREAD

**Issue by eliotsykes** [eliotsykes/real-world-rails#51]
I really need to get my act together and start a newsletter with what I find in these projects. 

At the moment I research these projects frequently and make some notes but don't share them widely enough. The biggest contribution I can make to the Rails community is to share these findings more. If you're interested subscribe to this GitHub issue and I'll update it once I've got a newsletter setup - aiming for early 2017!

**Comment by subratrout** [comment]
Hi Eliot, hope you have some plan to start the newsletter soon. Thank you

**Comment by eliotsykes** [comment]
Thanks for the nudge @subratrout 😃 - wow I really missed the self-imposed deadline.

For now, much of what I dig out of these Rails projects is testing related, which the essence of sometimes ends up in a rails-testing-toolbox repo. I recommend following/watching it if you want GitHub notifications whenever something new gets added to it: https://github.com/eliotsykes/rails-testing-toolbox
