### ISSUE TITLE
apps and engines paths contain only .git files after  "git submodule update --init"  is executed

### ISSUE THREAD

**Issue by apaokin** [eliotsykes/real-world-rails#571]
Good evening everyone!
Apps and engines paths contain only .git files after  "git submodule update --init" is executed, but .git folder is increased to 8 Gb.
I use git version 2.17.1.
Thank you in advance.

**Comment by Jberczel** [comment]
@apaokin - FYI, i just had the same issue.  I noticed that some of the existing apps and engines paths no longer exist:

apps/netguru-help
engines/o_cms

I removed those submodules (https://github.com/eliotsykes/real-world-rails#how-to-remove-a-git-submodule), and re-ran the `submodule update` command, and now I see the source code.

**Comment by Aesthetikx** [comment]
I also noticed there is some private module in apps/cartodb that fails to clone.
