### ISSUE TITLE
update branch names 

### ISSUE THREAD

**Issue by mpvosseller** [eliotsykes/real-world-rails#7911]
Several of the submodules have changed their default branch names. Most commonly they removed `master` and replaced it with `main`.

Below are the ones I found. Note that `apps/growstuff` changed to `dev`

apps/spree -> main
apps/discourse -> main
apps/errbit -> main
apps/calagator -> main
apps/24pullrequests -> main
apps/whitehall -> main
apps/growstuff -> dev 
apps/signonotron2 -> main
apps/publisher -> main
apps/frontend -> main
apps/csvlint -> main
apps/ruby-china -> main
apps/git-scm -> main
apps/parliamentary-questions -> main
apps/imminence -> main
apps/cfp-app -> main
apps/alonetone -> main
apps/alchemy_cms -> main
engines/administrate -> main
apps/libraries.io -> main
apps/ifme -> main
engines/shopify_app -> main
engines/rucaptcha -> main
engines/browse-everything -> main
engines/local_time -> main
apps/hyku -> main
apps/crimethinc-website -> main
engines/hyrax -> main
apps/dev.to -> main
apps/rubytoolbox -> main
apps/mastodon -> main
apps/identity-idp -> main
apps/theodinproject -> main

**Comment by eliotsykes** [comment]
Thanks @mpvosseller, handled in #7948
