### ISSUE TITLE
Maintenance of this project?

### ISSUE THREAD

**Issue by andyw8** [eliotsykes/real-world-rails#7921]
Hi Elliot :wave: 

It's been a while since there's been any updates to the repo (August 2021). It's a really valuable project and I would love to see it continue. Would you be interested in finding a new maintainer?

I saw that @posiczko has made some updates recent in the fork at https://github.com/posiczko/real-world-rails/

**Comment by eliotsykes** [comment]
Hi Andy. I hope to be able to get back to maintaining this repo in the near future. Glad to see a fork is being given some love 👍

**Comment by andyw8** [comment]
Hi @eliotsykes, it's been a year since your reply, do you have any updates to share?

**Comment by eliotsykes** [comment]
No updates. I'm taking a peek at it this morning.
